config/routes.rb
Rails.application.routes.draw do
  #devise routes
  devise_for :users,  :token_authentication_key => 'authentication_key'
  
  #customers routes
  resources :customers
  root "customers#index"
  post "customers/refresh_token" => "customers#refresh_token", as: 'refresh_path'
 
 # API routes
  namespace :api do
    namespace :v1 do
      resources :customers, only: [:create, :index, :show], defaults: {format: :json}
    end
  end

  

  # Example resource route with sub-resources:
  #   resources :products do
  #     resources :comments, :sales
  #     resource :seller
  #   end

  # Example resource route with more complex sub-resources:
  #   resources :products do
  #     resources :comments
  #     resources :sales do
  #       get 'recent', on: :collection
  #     end
  #   end

  # Example resource route with concerns:
  #   concern :toggleable do
  #     post 'toggle'
  #   end
  #   resources :posts, concerns: :toggleable
  #   resources :photos, concerns: :toggleable

  # Example resource route within a namespace:
  #   namespace :admin do
  #     # Directs /admin/products/* to Admin::ProductsController
  #     # (app/controllers/admin/products_controller.rb)
  #     resources :products
  #   end
end

app/models/concerns/tokenable.rb
module Tokenable
  extend ActiveSupport::Concern

  included do
    before_create :generate_token
  end

  protected

  def generate_token
    self.authentication_token = loop do
      random_token = SecureRandom.urlsafe_base64(nil, false)
      break random_token unless self.class.exists?(authentication_token: random_token)
    end
  end
end

app/models/customer.rb
class Customer < ActiveRecord::Base
	belongs_to :user
end

app/models/user.rb
class User < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable

  has_many :customers

  include Tokenable

  
end

app/controllers/api/v1/base_controller.rb
class Api::V1::BaseController < ApplicationController






end

app/controllers/api/v1/customers_controller.rb
class Api::V1::CustomersController < ApplicationController
 before_action :set_customer, only: [:show, :update, :destroy]

  def index
    @user = current_user
    @customers = @user.customers.all
    render json: @customers
  end

  def show
    @customer = Customer.find(params[:id])
    render json: @customer
  end

  def create
    @customer = Customer.new(customer_params)

    if @customer.save
      render json: @customer, status: :created, location: @customer
    else
      render json: @customer.errors, status: :unprocessable_entity
    end
  end

  def update
    @customer = Customer.find(params[:id])
    if @customer.update(customer_params)
      head :no_content
    else
      render json: @customer.errors, status: :unprocessable_entity
    end
  end

  def destroy
    @customer = Customer.find(params[:id])
    @customer.destroy
    head :no_content
  end

  private

    def set_customer
      @customer = Customer.find(params[:id])
    end

    def customer_params
      params.require(:customer).permit(:full_name, :email, :phone)
    end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
   protect_from_forgery with: :exception

  before_filter :after_token_authentication 

  def after_token_authentication
    if params[:authentication_key].present?
      @user = User.find_by_authentication_token(params[:authentication_key]) 
      sign_in @user if @user 
      redirect_to customers_path 
    end
  end

  protected

    def configure_permitted_parameters
      devise_parameter_sanitizer.for(:sign_up) { |u| u.permit( :email, :password, :password_confirmation, :authentication_token) }
      devise_parameter_sanitizer.for(:account_update) { |u| u.permit(:email, :password, :current_password, :authentication_token) }
    end
end

app/controllers/customers_controller.rb
class CustomersController < ApplicationController

  def index
  end

  def new
  	@customer = Customer.new
  end

  def create
  	@user = current_user
  	@customer = @user.customers.new(params_customer)
  	if @customer.save
  		redirect_to customers_path
  	else
  		render 'new'
  	end
  end

  def refresh_token
  	@user = current_user
  	@user.authentication_token = loop do
      random_token = SecureRandom.urlsafe_base64(nil, false)
      break random_token unless @user.class.exists?(authentication_token: random_token)
    end
    @user.update(:authentication_token => @user.authentication_token)
    redirect_to customers_path
	end

  private
  	def params_customer
  		params.require(:customer).permit(:full_name, :email, :phone, :user_id)
  	end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/customers_helper.rb
module CustomersHelper
end

app/views/customers/index.html.slim
- if user_signed_in?
	div id='documentation'
	  p
	  	Welcome to your developer dashboard This page allows you to track your usage of the API-TRAIN At the bottom of the page is your API Key which should replace “APIKEY” anywhere it appears in the documentation. For example will get you the forecast for Alcatraz (in case you need to use hyper-local weather predictions to aid in an escape). If anyone ever gets a hold of your API Key you should reset it immediately."
	
	div id='apikey'
		p
			= link_to 'APi contact', api_v1_customers_path

	div id='refresh'
		= form_tag(controller: 'customers', action: 'refresh_token', :method=>'post', :multipart => true) do
			= text_field_tag "API-KEY", current_user.authentication_token
			= submit_tag 'Refresh'
- else
	div id='documentation'
	  p
	    Welcome to your developer dashboard This page allows you to track your usage of the Forecast API. At the bottom of the page is your API Key which should replace “APIKEY” anywhere it appears in the documentation. For example will get you the forecast for Alcatraz (in case you need to use hyper-local weather predictions to aid in an escape). If anyone ever gets a hold of your API Key you should reset it immediately.

app/views/customers/new.html.slim
= form_for @customer do |t|
	= t.label :full_name
	= t.text_field :full_name
	br
	= t.label :email
	= t.email_field :email
	br
	= t.label :phone
	= t.text_field :phone
	br
	= t.submit "add contact"

app/views/layouts/application.html.slim
doctype html
html[lang="en"]
  head
    meta[charset="utf-8"]
    meta[name="viewport" content="width=device-width, initial-scale=1.0"]
    title
      = content_for?(:title) ? yield(:title) : "API-TRAIN"
    = stylesheet_link_tag    "application"
    = javascript_include_tag "application", 'data-turbolinks-track' => true
    = csrf_meta_tags
  body
    #content
      ul.breadcrumbs
        - if user_signed_in?
          li
            = link_to "deconnexion", destroy_user_session_path, method: :delete
          li
            = link_to "#{current_user.email}", customers_path
          li.current
            = link_to "add contact",  new_customer_path
        - else
          li
            = link_to "connexion", new_user_session_path
          li
            = link_to "s'inscrire", new_user_registration_path
      = yield